### ISSUE TITLE
Enforce implementation of Parcelable

### ISSUE THREAD

**Issue by JakeWharton** [frankiesardo/auto-parcel#22]
We occasionally forget to include `implements Parcelable` on our declarations which ends up failing at runtime. The processor should enforce that all classes annotated with `@AutoParcel` indeed include this declaration (either directly or from a base class) thus moving this to a compile-time validation.

I believe you can look at how `@AutoService` does verification and copy/paste most or all of its logic.

**Comment by artem-zinnatullin** [comment]
That's sad :(

Good news: it's very easy to add this check.

From my annotation processor:

```java
/**
 * Checks whether TypeElement directly implements required interface
 *
 * @param typeElement  type element to check
 * @param interfaceFQN fully qualified name of interface "package.name.InterfaceName"
 * @return true if TypeElement implements required interface, false otherwise
*/
public static boolean directlyImplementsInterface(TypeElement typeElement, String interfaceFQN) {
  for (TypeMirror interfaceTypeMirror : typeElement.getInterfaces()) {
      if (interfaceTypeMirror.toString().equals(interfaceFQN)) {
          return true;
      }
   }

   return false;
}
```

If you need to check that some of parent classes implements required interface, you can recursively check all enclosing classes, [but](https://github.com/google/auto/tree/master/value#restrictions-and-non-features):
> One @AutoValue class may not extend another. As explained in Effective Java, inheritance of value types simply doesn't work.

So this piece of code should be enough, @frankiesardo I can prepare PR for that if you don't mind

**Comment by JakeWharton** [comment]
I did not say we were extending another `@AutoParcel` class, I said we were extending a base class which includes the `Parcelable` declaration–a perfectly valid case.

**Comment by frankiesardo** [comment]
`implements Parcelable` is optional because `@AutoParcel` is effectively a superset of `@AutoValue` for Android. Do you guys use `@AutoValue` if you want an immutable model without implementing `Parcelable`?

**Comment by JakeWharton** [comment]
Yes. In fact, I almost filed a feature request of including the `@AutoValue` annotation in this library to make explicit the behavior between the two.

**Comment by frankiesardo** [comment]
That's slightly inconsistent with the rest of the design of `AutoValue` tho. If you implement Serializable you get the serializable  generated stuff. If you implement Parcelable, likewise. Nothing forces you to implement these interfaces if you simply want an immutable model: that's why it was originally just named `android.AutoValue`.

WRT AutoValue extensibility, do you know if it will be performed via custom annotations? In that case splitting `@AutoValue` and `@AutoParcel` makes sense, otherwise, not much.

**Comment by JakeWharton** [comment]
Ah, I didn't realize that serializable behavior existed (mostly because no one on earth should ever use serializable). That presents quite a quandary as I much prefer the compile-time validation but understand the behavior mixin approach based on interfaces.

As to AutoValue's future extensibility, I don't know if anything like that has been decided definitively. Or at least we haven't heard anything in a few months about it. If I was a guessing man it would be that you could hook into the normal generation from `@AutoValue` and potentially use additional annotations on the object to alter behavior. So in that case it'd be up to you the author of the extension as to whether you wanted to support implicit generation of parcelable based on implementing the interface or require the annotation and interface and do validation.

**Comment by artem-zinnatullin** [comment]
> I did not say we were extending another `@AutoParcel` class, I said we were extending a base class which includes the Parcelable declaration–a perfectly valid case.

My bad, sorry.

> Do you guys use `@AutoValue` if you want an immutable model without implementing `Parcelable`?

Yes.

> That's slightly inconsistent with the rest of the design of AutoValue tho. If you implement Serializable you get the serializable generated stuff. If you implement Parcelable, likewise. Nothing forces you to implement these interfaces if you simply want an immutable model: that's why it was originally just named android.AutoValue.

That makes sense, but I never used `@AutoParcel` without implementing `Parcelable`, just because name of the project and annotation is `@AutoParcel` :smile: 

> Yes. In fact, I almost filed a feature request of including the `@AutoValue` annotation in this library to make explicit the behavior between the two.

It'll break a lot of projects: two libraries would declare same classes, but it'll really make behavior explicit.

I think it's okay to require implementing `Parcelable` for classes annotated with `@AutoParcel`, @frankiesardo don't you think so? Or may be it's better to rename project and annotation to `@AndroidAutoValue` and leave optional `Parcelable`, just thoughts.

**Comment by JakeWharton** [comment]
Looks like this won't be a thing with extensions.
