### ISSUE TITLE
Differences to auto-value-parcel

### ISSUE THREAD

**Issue by PaulWoitaschek** [frankiesardo/auto-parcel#41]
Congrats to the 1.0 release.

Not really an issue, but what is the difference to [auto-value-parcel](https://github.com/rharter/auto-value-parcel)? Is there something one can that the others can't?

**Comment by Rainer-Lang** [comment]
I only know after switching to 1.0.1 I got many many errors - still trying(!) to fix all.

**Comment by Rainer-Lang** [comment]
But it's a bug in AutoValue.

**Comment by frankiesardo** [comment]
Thanks @PaulWoitaschek. `auto-value-parcel` is more recent and evolving quickly, adding new interesting features. Most of those are in my roadmap as well but I'm moving a bit more slowly. `auto-parcel` has been successfully used in production for over two years and has a large use base, so not breaking other people builds is a top priority.

I would say if you want the bleeding edge features give `auto-value-parcel` a go, otherwise stick with the more widely used `auto-parcel`.
